
### Retrieve Schema by ID
< {%
    request.variables.set("id", "1")
%}
GET {{domain}}/schema-registry/{{id}}
Accept: application/vnd.apache.schema-avro+json;charset=UTF-8

### Register new Schema
< {%
    request.variables.set("subject", "obs.statement-line")
%}
POST {{domain}}/schema-registry/{{subject}}
Accept: application/vnd.apache.schema-avro+json;charset=UTF-8
Content-Type: application/vnd.apache.schema-avro+json

< ../../../observable-streams-demo/src/main/avro/obs.statement-line.avsc

### Register new Schema version
< {%
    request.variables.set("subject", "something")
    request.variables.set("version", "something")
%}
PUT {{domain}}/schema-registry/{{subject}}}/{{version}}}
Accept: application/vnd.apache.schema-avro+json;charset=UTF-8
Content-Type: application/vnd.apache.schema-avro+json

