
### Describe topics
GET {{domain}}/topics?topics=obs.approved-statement-lines
Accept: application/json

### Create new Topic
POST {{domain}}/topics
Accept: application/json
Content-Type: application/json

{
    "name": "obs.approved-statement-lines",
    "numPartitions": 5,
    "configs": {
        "retention.ms": "3600000"
    }
}